export enum ProfilKategoriEnum {
	SEJARAH = 'sejarah',
	LETAK_GEOGRAFIS_DAN_PETA_DESA = 'letak-geografis-dan-peta-desa',
	VISI_DAN_MISI = 'visi-dan-misi',
	STRUKTUR_PEMERINTAHAN_DESA = 'struktur-pemerintahan-desa',
	JUMLAH_PENDUDUK_DAN_DATA_UMUM = 'jumlah-penduduk-dan-data-umum'
}

export enum BeritaPengumumanKategoriEnum {
    BERITA = 'berita',
	PENGUMUMAN = 'pengumuman'
}

export enum AdminKategoriEnum {
    ADMIN = 'admin',
    SUPER_ADMIN = 'superadmin',
}

export enum AdminLogKategoriEnum {
	CREATE_PROFIL = 'CREATE_PROFIL',
	UPDATE_PROFIL = 'UPDATE_PROFIL',
	DELETE_PROFIL = 'DELETE_PROFIL',
	CREATE_BERITA_DAN_PENGUMUMAN = "CREATE_BERITA_DAN_PENGUMUMAN",
	UPDATE_BERITA_DAN_PENGUMUMAN = "UPDATE_BERITA_DAN_PENGUMUMAN",
	DELETE_BERITA_DAN_PENGUMUMAN = "DELETE_BERITA_DAN_PENGUMUMAN",
	CREATE_GALERI = "CREATE_GALERI",
    UPDATE_GALERI = "UPDATE_GALERI",
    DELETE_GALERI = "DELETE_GALERI",
	CREATE_PRODUK_UNGGULAN = "CREATE_PRODUK_UNGGULAN",
	UPDATE_PRODUK_UNGGULAN = "UPDATE_PRODUK_UNGGULAN",
	DELETE_PRODUK_UNGGULAN = "DELETE_PRODUK_UNGGULAN",
	UPDATE_KONTAK_DESA = "UPDATE_KONTAK_DESA",
	UPDATE_ASPIRASI_FORM = "UPDATE_ASPIRASI_FORM",
	DELETE_ASPIRASI_FORM = "DELETE_ASPIRASI_FORM",
	UPDATE_ADMIN = "UPDATE_ADMIN",
	LOGIN = "LOGIN",
	LOGOUT = "LOGOUT",
    CREATE_LINK_WEB = 'create_link_web',
    UPDATE_LINK_WEB = 'update_link_web',
    DELETE_LINK_WEB = 'delete_link_web',
    CREATE_ADMIN = "CREATE_ADMIN",
    DELETE_ADMIN = "DELETE_ADMIN",
}